config/routes.rb
Rails.application.routes.draw do
  get "likes/create"
  get "likes/destroy"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, controllers: {
   registrations: "users/registrations",
   sessions:       "users/sessions",
   passwords: "users/passwords",
   omniauth_callbacks: "users/omniauth_callbacks"
   }

  root "homes#index"
  get "how_to_use", to: "homes#how_to_use"
  get "privacy", to: "homes#privacy"
  get "terms", to: "homes#terms"

  devise_scope :user do
    delete "logout", to: "users/sessions#destroy", as: :logout
  end

  resources :posts, only: %i[index new create show edit update destroy] do
    resource :likes, only: %i[create destroy index]
  end
  resources :likes, only: [ :index ]

  resources :marches, only: %i[index new create show edit update destroy] do
    resources :join_marches, only: [ :index, :update ], controller: "marches/join_marches"
    member do
      get :participants_info
      get :participants_info_edit
      patch :participants_info_update
    end
    collection do
      get :bookmarks  # /marches/bookmarks
    end
    resources :bookmarks, only: [ :create, :destroy ]
  end

  resource :mypage, only: [ :show, :edit, :update ]

  namespace :mypage do
    resources :join_marches, only: [ :create, :index, :destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  mount_uploaders :images, ImageUploader
  has_many :likes

  require "uri"
  require "cgi"

  def youtube_video_id
    return nil if youtube_url.blank?

    uri = URI.parse(youtube_url)

    if uri.host.include?("youtu.be")
      uri.path[1..] # "/abc123" → "abc123"
    else
      query_params = CGI.parse(uri.query || "")
      query_params["v"]&.first
    end
    rescue URI::InvalidURIError
    nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
  def index
    @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

      if @post.save
        redirect_to posts_path, notice: "todoを作成されました！"
      else
        flash.now[:alert] = "タイトルを入力してください！"  # ← alertに変更
        render :new, status: :unprocessable_entity
      end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
       redirect_to post_path(@post), success: t("defaults.flash_message.updated", item: Post.model_name.human)
    else
      flash.now[:danger] = t("defaults.flash_message.not_updated", item: Post.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "削除しました"
  end


  private

  def post_params
    params.require(:post).permit(:title, :body, { images: [] }, :youtube_url)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="max-w-4xl mx-auto bg-white rounded-lg shadow-md p-6 mt-24">
  <%= form_with(model: @post, local: true) do |form| %>
    <div class="mb-4">

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2">
        画像
      </label>
      <%= form.file_field :images, multiple: true, accept: "image/*", class: "w-full px-32 py-24 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none" %>
    </div>

      <label class="block text-gray-700 text-sm font-bold mb-2">
        タイトル
      </label>
      <%= form.text_field :title, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2">
        本文
      </label>
      <%= form.text_area :body, class: "w-full px-32 py-24 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none" %>
    </div>

    <div class="field">
      <%= form.label :youtube_url, "YouTube動画URL" %>
      <%= form.text_field :youtube_url, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

  <div class="mb-4">
    <%= form.submit "更新する", class: "inline-flex items-center justify-center px-6 py-3 font-medium text-white bg-gradient-to-r from-orange-500 to-orange-600 rounded-full hover:from-orange-600 hover:to-orange-700 shadow-sm hover:shadow-md lg:px-4 lg:py-2 lg:w-auto transition-all duration-200" %>
  </div>
  <% end %>
</div>

app/views/posts/index.html.erb
 <div class="container mx-auto px-4 py-6">
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <% @posts.each do |post| %>
      <div class="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-shadow">
        <!-- 画像エリア -->
        <% if post.images.present? %>
          <%= image_tag post.images.first.url, class: "w-full h-48 object-cover" %>
        <% else %>
          <div class="bg-gray-200 w-full h-full flex items-center justify-center">
            <span class="text-gray-500">画像なし</span>
          </div>
        <% end %>
        <!-- コンテンツエリア -->
        <div class="p-4">
          <h3 class="text-lg font-semibold mb-2"><%= post.title %></h3>
          <p class="text-gray-600 text-sm"><%= truncate(post.body, length: 100) %></p>
         <%= link_to "詳細を見る",post_path(post), 
                class: "text-blue-500 hover:text-blue-700 text-sm font-medium" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="max-w-4xl mx-auto bg-white rounded-lg shadow-md p-6 mt-24">
  <%= form_with(model: @post) do |form| %>

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2">
        画像
      </label>
      <%= form.file_field  :images, multiple: true, accept: "image/*", class: "w-full px-32 py-24 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none" %>
    </div>

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2">
        タイトル
      </label>
      <%= form.text_field :title, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2">
        本文
      </label>
      <%= form.text_area :body, class: "w-full px-32 py-24 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none" %>
    </div>

    <div class="field">
      <%= form.label :youtube_url, "YouTube動画URL" %>
      <%= form.text_field :youtube_url, class: "w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

  <div class="mb-4">
    <%= form.submit "投稿する", class: "inline-flex items-center justify-center px-6 py-3 font-medium text-white bg-gradient-to-r from-orange-500 to-orange-600 rounded-full hover:from-orange-600 hover:to-orange-700 shadow-sm hover:shadow-md lg:px-4 lg:py-2 lg:w-auto transition-all duration-200" %>
  </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container mx-auto pt-12">
  <h1 class="text-2xl font-bold mb-6">投稿詳細</h1>
  <article class="bg-white rounded-lg shadow-md">
    <div class="p-6">
      <div class="md:flex md:space-x-6">
        <div class="md:w-1/4">
          <!-- 画像部分 -->
          <% if @post.images.present? %>
            <% @post.images.each do |image| %>
              <%= image_tag image.url, class: "w-full h-48 object-cover rounded-lg" %>
            <% end %>
          <% end %>
        </div>
        <div class="md:w-3/4">
          <!-- タイトルと本文部分 -->
          <h3 class="text-xl font-semibold mb-4"><%= @post.title %></h3>
          <p class="text-gray-700"><%= simple_format(@post.body) %></p>
        </div>
        <div class="md:w-3/4">
          <% if @post.youtube_video_id.present? %>
            <iframe width="450" height="315"
              src="https://www.youtube.com/embed/<%= @post.youtube_video_id %>"
              frameborder="0" allowfullscreen>
            </iframe>
          <% end %>
        </div>
      </div>
      
      <!-- 編集・削除ボタン -->
      <div class="flex justify-end mt-6 space-x-3">
        <%= link_to "一覧に戻る", posts_path, class: "inline-flex items-center px-4 py-2 border border-blue-300 shadow-sm text-sm font-medium rounded-md text-blue-700 bg-white hover:bg-blue-100 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors duration-200"%>
        <%= link_to "編集", edit_post_path(@post), 
        id: "button-edit-#{@post.id}",
        class: "inline-flex items-center px-4 py-2 border border-orange-300 shadow-sm text-sm font-medium rounded-md text-orange-700 bg-white hover:bg-orange-100 focus:outline-none focus:ring-2 focus:ring-orange-600 transition-colors duration-200" %>
  
        <%= link_to "削除", post_path(@post), 
        id: "button-delete-#{@post.id}",
        data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" },
        class: "inline-flex items-center px-4 py-2 border border-red-300 shadow-sm text-sm font-medium rounded-md text-red-900 bg-white hover:bg-red-100 focus:outline-none focus:ring-2 focus:ring-red-600 transition-colors duration-200" %>
        <% if current_user.liked?(@post) %>
          <%= button_to post_likes_path(@post), method: :delete, class: "text-2xl text-red-500" do %>
          <i class="fas fa-heart"></i>
          <% end %>
        <% else %>
          <%= button_to post_likes_path(@post), method: :post, class: "text-2xl text-gray-500" do %>
          <i class="far fa-heart"></i>
          <%= @post.likes.count %> 
          <% end %>
        <% end %>
     </div>
    </div>
  </article>
</div>